# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  spark-master:
    container_name: spark-master
    image: docker.arvancloud.ir/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_MASTER_OPTS="-Dspark.master.rest.enabled=true"
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - '8080:8080'
      - '6066:6066'
  spark-worker:
    container_name: spark-worker
    image: docker.arvancloud.ir/bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - '8081:8081'
      - "4040-4050:4040-4050" # Spark Application UIs
    volumes:
      - ${LOG_PATH_ON_HOST}:${LOG_PATH_ON_CONTAINER}:rw

  spark-history:
    container_name: spark-history
    image: docker.arvancloud.ir/bitnami/spark:3.5
    environment:
      - SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=${LOG_URI_ON_CONTAINER}"
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - '18080:18080'  # History Server Default port
    volumes:
      - ${LOG_PATH_ON_HOST}:${LOG_PATH_ON_CONTAINER}:rw  # Local directory mapped to /tmp/spark-events in the container
    command: ["sh", "-c", "./sbin/start-history-server.sh"]