services:
  spark-master:
    container_name: spark-master
    image: docker.arvancloud.ir/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_MASTER_OPTS="-Dspark.master.rest.enabled=true"
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - '8080:8080'
      - '6066:6066'
    volumes:
      - ${SPARK_APPLICATION_JAR_DIRECTORY}:/tmp/spark-app-jars/
    networks:
      - spark-net

  spark-worker-1: &spark-worker-service-template
    image: docker.arvancloud.ir/bitnami/spark:3.5
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1100m
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - "8081:8081"
      - "4040-4045:4040-4045"  # Spark Application UIs
    volumes:
      - ${LOG_PATH_ON_HOST}:${LOG_PATH_ON_CONTAINER}
      - ${SPARK_APPLICATION_JAR_DIRECTORY}:/tmp/spark-app-jars/
    networks:
      - spark-net

  spark-worker-2: &spark-worker-service-template
    image: docker.arvancloud.ir/bitnami/spark:3.5
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1100m
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - "8082:8082"  # Different port mapping for worker-2
      - "5040-5045:4040-4045"  # Different range for Spark Application UIs
    volumes:
      - ${LOG_PATH_ON_HOST}:${LOG_PATH_ON_CONTAINER}
      - ${SPARK_APPLICATION_JAR_DIRECTORY}:/tmp/spark-app-jars/
    networks:
      - spark-net

  spark-history:
    container_name: spark-history
    image: docker.arvancloud.ir/bitnami/spark:3.5
    environment:
      - SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=${LOG_URI_ON_CONTAINER}"
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - '18080:18080'  # History Server Default port
    volumes:
      - ${LOG_PATH_ON_HOST}:${LOG_PATH_ON_CONTAINER}  # Local directory mapped to /tmp/spark-events in the container
    command: ["sh", "-c", "./sbin/start-history-server.sh"]
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge